### ISSUE TITLE
monomouse-input fails to compile on Windows against windows = 0.62 (call sites not ported)

### ISSUE THREAD

**Issue by RickyVaughn2** [RickyVaughn2/monomouse#1]
## Summary

`monomouse-input` does not compile on Windows against `windows = "0.62"` (the version pinned in `crates/monomouse-input/Cargo.toml` since `dac593e`). The Cargo.toml bump from 0.61 → 0.62 in that commit did not include the corresponding call-site updates in `crates/monomouse-input/src/windows/`, so a fresh `cargo build --release` fails with 8 errors before any binary is produced.

This is the same set of compile errors that existed under 0.61; the API surfaces involved are unchanged between 0.61 and 0.62.

## Environment

- OS: Windows 11 Pro 26200
- Rust: `rustc 1.95.0 (59807616e 2026-04-14)` (stable-x86_64-pc-windows-msvc)
- Toolchain: VS Build Tools 2022 17.14, Windows SDK 10.0.26100
- Resolved crate (Cargo.lock): `windows 0.62.2`
- Repo HEAD: `dac593e` "Update windows crate to 0.62, fix GUI monitor placement"

## Reproduction

```
git clone https://github.com/RickyVaughn2/monomouse
cd monomouse
cargo build --release
```

## Errors

```
error[E0432]: unresolved import `windows::Win32::Foundation::BOOL`
 --> crates/monomouse-input/src/windows/detect.rs:5:34

error[E0432]: unresolved import `windows::Win32::UI::Input::KeyboardAndMouse::GetCursorPos`
  --> crates/monomouse-input/src/windows/capture.rs:19:5

error[E0308]: mismatched types
  --> crates/monomouse-input/src/windows/detect.rs:24:13
  expected `Option<HDC>`, found `HDC`

error[E0277]: the `?` operator cannot be applied to type `BOOL`
  --> crates/monomouse-input/src/windows/detect.rs:23:9

error[E0610]: `u32` is a primitive type and therefore doesn't have fields
  --> crates/monomouse-input/src/windows/capture.rs:182:45  (data.mouseData.0)
  --> crates/monomouse-input/src/windows/capture.rs:189:45
  --> crates/monomouse-input/src/windows/capture.rs:196:50
  --> crates/monomouse-input/src/windows/capture.rs:208:50
```

## Root cause and required fixes

The Windows-platform module was written against an older `windows-rs` API. Five distinct changes are needed:

1. **`BOOL` is no longer re-exported from `Win32::Foundation`** — it now lives at `windows::core::BOOL`.
   In `detect.rs:5`, change to `use windows::core::BOOL;` (and drop `BOOL` from the `Foundation` import).

2. **`GetCursorPos` moved from `Win32::UI::Input::KeyboardAndMouse` to `Win32::UI::WindowsAndMessaging`.**
   In `capture.rs:19`, fold `GetCursorPos` into the existing `WindowsAndMessaging` use group.

3. **`EnumDisplayMonitors` first parameter is now `Option<HDC>`.**
   In `detect.rs:24`, change `HDC::default()` to `None`.

4. **`EnumDisplayMonitors` returns `BOOL`, not `Result<()>`.**
   In `detect.rs:28`, change `)?;` to `).ok()?;` (the `BOOL::ok()` method on `windows-result` converts to `Result<()>`).

5. **`MSLLHOOKSTRUCT.mouseData` is now a plain `u32`, not a tuple struct.**
   In `capture.rs:182,189,196,208`, change `data.mouseData.0` to `data.mouseData` (4 sites).

## Build outcome with these fixes applied

With those 5 changes, the workspace builds cleanly in release mode on Windows 11 + MSVC; all three binaries (`monomouse-server.exe`, `monomouse-client.exe`, `monomouse-gui.exe`) link successfully. The only remaining diagnostics are `unsafe_op_in_unsafe_fn` warnings from edition 2024 — non-blocking.

## Note

A patch with these fixes is sitting on a local-only branch on a downstream Windows machine; happy to open a PR if useful, otherwise this issue contains everything needed to reproduce and fix at source.
